ame: Client CI (lint & build)

on:
  push:
    paths:
      - "client/**"
      - ".github/workflows/client-ci.yml"
  pull_request:
    paths:
      - "client/**"

jobs:
  client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20 with npm cache
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Upload dist
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: client-dist
          path: client/dist
