jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [client, wiki]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint ${{ matrix.app }}
        run: npm run lint -w apps/${{ matrix.app }}

      - name: Build ${{ matrix.app }}
        run: npm run build -w apps/${{ matrix.app }}

      - name: Check build output
        run: ls -la apps/${{ matrix.app }}/dist
