name: Backend CI (build)

on:
  push:
    paths:
      - "server/**"
      - ".github/workflows/backend-ci.yml"
  pull_request:
    paths:
      - "server/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20 with npm cache
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "server/package-lock.json"

      - name: Install dependencies
        run: npm i

      - name: Build server
        run: npm run build

      - name: Fix imports
        run: node fix-imports.js

      - name: Check server build output
        run: ls -la dist
