name: Build and Push to Deployment Repo

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: |
            frontend/package-lock.json
            server/package-lock.json

      - name: Install Backend Dependencies
        working-directory: ./server
        run: npm ci

      - name: Build Backend
        working-directory: ./server
        run: npm run build

      - name: Install Frontend Root Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build Client App
        working-directory: ./frontend/apps/client
        run: |
          npm run build
          echo "Client build completed"

      - name: Build Wiki App
        working-directory: ./frontend/apps/wiki
        run: |
          npm run build
          echo "Wiki build completed"

      - name: Prepare Deployment Directory
        run: |
          mkdir -p out/client
          mkdir -p out/wiki
          mkdir -p out/server

          # Copy backend package.json to root
          cp server/package*.json out/

          # Copy ENTIRE server directory structure (not just dist contents)
          cp -r server/dist/* out/server/
          # Also copy any config files if they're not in dist
          if [ -d "server/src/config" ]; then
            cp -r server/src/config out/server/config 2>/dev/null || true
          fi

          # Copy frontend builds directly
          cp -r frontend/apps/client/dist/* out/client/
          cp -r frontend/apps/wiki/dist/* out/wiki/

          echo "Deployment directory prepared"

      - name: Create Production README
        run: |
          cat > out/README.md <<EOF
          # OmniEconomy Production Build

          Automated deployment created on: $(date +'%Y-%m-%d %H:%M:%S')

          ## Structure
          - \`/client\` - Built client application
          - \`/wiki\` - Built wiki application
          - \`/server\` - Built backend server files
          - \`package.json\` - Backend dependencies (root level)

          ## Deployment
          1. Install backend dependencies: \`npm ci --production\`
          2. Set environment variables
          3. Start backend: \`npm start\`
          4. Serve frontend with nginx or similar

          ## Environment Variables Required
          - DATABASE_URL
          - JWT_SECRET
          - PORT
          (See original repo for full list)
          EOF

      - name: Create Deployment Script
        run: |
          cat > out/deploy.sh <<'EOF'
          #!/bin/bash
          set -e

          echo "Starting OmniEconomy Deployment..."

          # Backend
          echo "Installing backend dependencies..."
          npm ci --production

          # Check for .env
          if [ ! -f .env ]; then
            echo "Warning: .env not found!"
            echo "Please create it with required environment variables"
          fi

          echo "Deployment preparation complete!"
          echo "Start backend with: npm start"
          echo "Serve /client and /wiki with your web server"
          EOF

          chmod +x out/deploy.sh

      - name: Push to Deployment Repository
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          DEPLOY_REPO: "matejhozlar/omnieconomy-xyz-prod"
        run: |
          cd out

          # Initialize git
          git init
          git checkout -b main

          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Add remote (NO TRAILING SLASH!)
          git remote add origin "https://${DEPLOY_TOKEN}@github.com/${DEPLOY_REPO}.git"

          # Fetch if repo exists
          git fetch origin main 2>/dev/null || echo "Remote branch doesn't exist yet, will create it"

          # Add all files
          git add -A

          # Commit
          git commit -m "Automated deployment on $(date +'%Y-%m-%d %H:%M:%S')"

          # Push (force push to overwrite)
          git push -f origin main

          echo "Successfully pushed to deployment repository"
