name: Frontend CI (lint & build)

on:
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-ci.yml"
  pull_request:
    paths:
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20 with npm cache
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      - name: Install dependencies (monorepo root)
        run: npm ci

      - name: Lint client
        run: npm run lint -w apps/client

      - name: Lint wiki
        run: npm run lint -w apps/wiki

      - name: Build client
        run: npm run build -w apps/client

      - name: Build wiki
        run: npm run build -w apps/wiki

      - name: Check client build output
        run: ls -la apps/client/dist

      - name: Check wiki build output
        run: ls -la apps/wiki/dist
